#!/usr/bin/perl
use strict;
use warnings;
use Horse;
use Mouse;

my %beast = (
    Mickey => 'Mouse',
    Ed     => 'Horse',
);

for my $name ( sort keys %beast ) {
    my $b = $beast{$name}->new( name => $name );
    print $b->name, " is ", $b->color, "\n";
    $b->speak;
}
